/**
 * Dữ liệu sản phẩm dùng chung (trang chủ, cửa hàng, danh mục).
 * category: vot | cau | giay-ao | tui-phu-kien
 */
window.TRIPLET_CATEGORY_META = {
  vot: {
    title: "Vợt cầu lông",
    blurb: "Cân bằng, đầu nặng, siêu nhẹ — chọn theo lối chơi.",
  },
  cau: {
    title: "Cầu lông",
    blurb: "Lông vịt thi đấu, cầu tập nhựa, tốc độ 76–78.",
  },
  "giay-ao": {
    title: "Giày & trang phục",
    blurb: "Giày bám sân, áo quần thấm mồ hôi.",
  },
  "tui-phu-kien": {
    title: "Túi & phụ kiện",
    blurb: "Túi vợt, quấn cán, cước, băng hỗ trợ.",
  },
};

window.TRIPLET_PRODUCTS = [
  {
    id: "p-racket-1",
    name: "Vợt all-round cân bằng — khung carbon",
    price: 2290000,
    image: "Images/vot-cau-long-1.png",
    thumb: "Images/vot-cau-long-1.png",
    tag: "Vợt",
    category: "vot",
    featured: true,
    alt: "Vợt cầu lông carbon",
  },
  {
    id: "p-racket-2",
    name: "Vợt đầu nặng 4U — tối ưu tấn công smashes",
    price: 2690000,
    image: "Images/vot-cau-long-2.jpg",
    thumb: "Images/vot-cau-long-2.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông tấn công",
  },
  {
    id: "p-racket-3",
    name: "Vợt siêu nhẹ 6U — người mới & đánh đôi",
    price: 1190000,
    image: "Images/vot-cau-long-3.jpg",
    thumb: "Images/vot-cau-long-3.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông nhẹ",
  },
  {
    id: "p-racket-4",
    name: "Vợt siêu nặng 6U — chuyên nghiệp & đánh đôi",
    price: 1890000,
    image: "Images/vot-cau-long-4.jpg",
    thumb: "Images/vot-cau-long-4.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông nặng",
  },
  {
    id: "p-racket-5",
    name: "Power 99 — 6U | Đánh Đôi | Siêu nhẹ",
    price: 2690000,
    image: "Images/vot-cau-long-5.jpg",
    thumb: "Images/vot-cau-long-5.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông 99 siêu nhẹ",
  },
  {
    id: "p-racket-6",
    name: "Speed 77 — 6U | Đánh Đôi",
    price: 1420000,
    image: "Images/vot-cau-long-6.jpg",
    thumb: "Images/vot-cau-long-6.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông 77",
  },
  {
    id: "p-racket-7",
    name: "Drive X — 6U | Đánh Đôi",
    price: 2340000,
    image: "Images/vot-cau-long-7.jpg",
    thumb: "Images/vot-cau-long-7.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông Drive X",
  },
   {
    id: "p-racket-8",
    name: "Control Z — 6U | Đánh Đôi",
    price: 1280000,
    image: "Images/vot-cau-long-8.jpg",
    thumb: "Images/vot-cau-long-8.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông Control Z",
  },
   {
    id: "p-racket-9",
    name: "Aero 77 — 6U | Đánh Đôi",
    price: 1200000,
    image: "Images/vot-cau-long-9.jpg",
    thumb: "Images/vot-cau-long-9.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông Aero 77",
  },
  {
    id: "p-racket-10",
    name: "Turbo 99 — 6U | Đánh Đôi",
    price: 2300000,
    image: "Images/vot-cau-long-10.jpg",
    thumb: "Images/vot-cau-long-10.jpg",
    tag: "Vợt",
    category: "vot",
    featured: false,
    alt: "Vợt cầu lông Turbo 99",
  },
  {
    id: "p-shuttle-1",
    name: "Hộp 12 quả cầu tốc độ 77 — thi đấu",
    price: 185000,
    image: "Images/hop-cau-long.jpg",
    thumb: "Images/hop-cau-long.jpg",
    tag: "Cầu",
    category: "cau",
    featured: true,
    alt: "Cầu lông thi đấu",
  },
  {
    id: "p-shuttle-2",
    name: "Túi 6 quả cầu nhựa tập — bền cho sân tập",
    price: 75000,
    image: "Images/hop-cau-long-2.jpg",
    thumb: "Images/hop-cau-long-2.jpg",
    tag: "Cầu",
    category: "cau",
    featured: false,
    alt: "Cầu nhựa tập",
  },
  {
    id: "p-shuttle-3",
    name: "Hộp 10 quả cầu nhựa tổng hợp — dành cho người mới tập",
    price: 12000,
    image: "Images/hop-cau-long-3.jpg",
    thumb: "Images/hop-cau-long-3.jpg",
    tag: "Cầu",
    category: "cau",
    featured: false,
    alt: "Cầu nhựa tập",
  },
  {
    id: "p-shuttle-4",
    name: "Cầu lông thi đấu tiêu chuẩn — tốc độ 76, chính xác cao",
    price: 125000,
    image: "Images/hop-cau-long-4.jpg",
    thumb: "Images/hop-cau-long-4.jpg",
    tag: "Cầu",
    category: "cau",
    featured: false,
    alt: "Cầu nhựa tập",
  },
   {
    id: "p-shuttle-5",
    name: "Ống 12 quả cầu lông Ba Sao — độ bền cao, bay ổn định",
    price: 175000,
    image: "Images/hop-cau-long-5.jpg",
    thumb: "Images/hop-cau-long-5.jpg",
    tag: "Cầu",
    category: "cau",
    featured: false,
    alt: "Cầu nhựa tập",
  },
  {
    id: "p-shuttle-6",
    name: "Ống cầu lông tốc độ 78 — bay nhanh, lực đi mạnh",
    price: 285000,
    image: "Images/hop-cau-long-6.jpg",
    thumb: "Images/hop-cau-long-6.jpg",
    tag: "Cầu",
    category: "cau",
    featured: false,
    alt: "Cầu nhựa tập",
  },
  {
    id: "p-shuttle-7",
    name: "Quả cầu lông vũ YONEX — dòng cao cấp cho giải đấu",
    price:  165000,
    image: "Images/hop-cau-long-7.jpg",
    thumb: "Images/hop-cau-long-7.jpg",
    tag: "Cầu",
    category: "cau",
    featured: false,
    alt: "Cầu nhựa tập",
  },
  {
    id: "p-shuttle-8",
    name: "Quả cầu lông đèn LED — chuyên dụng chơi ban đêm",
    price:  543000,
    image: "Images/hop-cau-long-8.jpg",
    thumb: "Images/hop-cau-long-8.jpg",
    tag: "Cầu",
    category: "cau",
    featured: false,
    alt: "Cầu nhựa tập",
  },
  {
    id: "p-shoe-1",
    name: "Giày cầu lông đế kép chống trượt",
    price: 1590000,
    image: "Images/giay-cau-long.jpg",
    thumb: "Images/giay-cau-long.jpg",
    tag: "Giày",
    category: "giay-ao",
    featured: true,
    alt: "Giày cầu lông",
  },
  {
    id: "p-shoe-2",
    name: "Giày indoor đệm EVA — ôm chân chắc chắn",
    price: 1740000,
    image: "Images/giay-cau-long-2.jpg",
    thumb: "Images/giay-cau-long-2.jpg",
    tag: "Giày",
    category: "giay-ao",
    featured: false,
    alt: "Giày thể thao indoor",
  },
  {
    id: "p-shirt-1",
    name: "Áo thi đấu Dry-fit thoáng khí",
    price: 350000,  
    image: "Images/ao-thi-dau.jpg",
    thumb: "Images/ao-thi-dau.jpg",
    tag: "Trang phục",
    category: "giay-ao",
    featured: true,
    alt: "Áo thể thao dry-fit",
  },
  {
    id: "p-short-1",
    name: "Quần thi đấu co giãn 4 chiều",
    price: 290000,
    image: "Images/quan-thi-dau.jpg",
    thumb: "Images/quan-thi-dau.jpg",
    thumb: "Images/quan-thi-dau.jpg",
    tag: "Trang phục",
    category: "giay-ao",
    featured: false,
    alt: "Quần thể thao",
  },
  {
    id: "p-bag-1",
    name: "Túi đựng 6 vợt có ngăn giày riêng",
    price: 890000,
    image: "Images/tui-dung.jpg",
    thumb: "Images/tui-dung.jpg",
    tag: "Túi",
    category: "tui-phu-kien",
    featured: true,
    alt: "Túi đựng vợt",
  },
  {
    id: "p-bag-2",
    name: "Balo 2 ngăn — đựng vợt + đồ cá nhân",
    price: 720000,
    image: "Images/tui-dung-2.jpg",
    thumb: "Images/tui-dung-2.jpg",
    tag: "Túi",
    category: "tui-phu-kien",
    featured: false,
    alt: "Balo thể thao",
  },
  {
    id: "p-grip-1",
    name: "Cuộn quấn cán chống trơn — combo 3 cuộn",
    price: 120000,
    image: "Images/cuon-quan-cam.jpg",
    thumb: "Images/cuon-quan-cam.jpg",
    tag: "Phụ kiện",
    category: "tui-phu-kien",
    featured: true,
    alt: "Phụ kiện thể thao",
  },
  {
    id: "p-string-1",
    name: "Cuộn cước 10m độ bền cao — BG65 tương đương",
    price: 195000,
    image: "Images/cuoc-cau-long.jpg",
    thumb: "Images/cuoc-cau-long.jpg",
    tag: "Phụ kiện",
    category: "tui-phu-kien",
    featured: false,
    alt: "Dây cước vợt",
  },
  {
    id: "p-wrist-1",
    name: "Băng cổ tay thấm mồ hôi — đôi",
    price: 89000,
    image: "Images/bang-co-tay.jpg",
    thumb: "Images/bang-co-tay.jpg",
    tag: "Phụ kiện",
    category: "tui-phu-kien",
    featured: false,
    alt: "Băng cổ tay thể thao",
  },
];
